INSERT INTO author_table (id, author_name, second_name) VALUES (1, 'Lev', 'Tolstoi');
INSERT INTO author_table (id, author_name, second_name) VALUES (2, 'Andjei', 'Sopkovskiy');
INSERT INTO author_table (id, author_name, second_name) VALUES (3, 'Aleksandr', 'Pushkin');
INSERT INTO books_table (id, book_name,author_id) VALUES (1, 'Spring Boot Recipes',1);
INSERT INTO books_table (id, book_name,author_id) VALUES (2, 'English Legends',2);
INSERT INTO books_table (id, book_name,author_id) VALUES (3, 'Robinson Crusoe',3);
INSERT INTO books_table (id, book_name,author_id)VALUES (4, 'Peter Pen',1);
INSERT INTO books_table (id, book_name,author_id)VALUES  (5, 'The Witcher',3);
INSERT INTO books_table (id, book_name,author_id)VALUES (6, 'The Red Hat',2);
INSERT INTO books_table (id, book_name,author_id) VALUES (7, 'Wolves',1);
INSERT INTO books_table (id, book_name,author_id) VALUES (8, 'The Legend of Warcraft',1);